version: '3.1'

services:
  php-apache:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./project/:/var/www/html/

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8080:80"

volumes:
  db_data: